### ISSUE TITLE
Improve update-trader-prices job

### ISSUE THREAD

**Issue by Razzmatazzz** [the-hideout/tarkov-crons#24]
The update-trader-prices job currently [looks up a particular trade based on the trade id](https://github.com/the-hideout/tarkov-crons/blob/3bfed2dde67c54cfc0b68e089f97961f924940bf/jobs/update-trader-prices.js#L25-L34). Using the item id instead would be a bit more resilient.

**Comment by austinhodak** [comment]
Fixed in #26
